akarneliuk/pygnmi

- pygnmi/arg_parser.py
- pygnmi/path_generator.py
Fixes these deprecation warnings (which are visible when python is launched with -W flag or when run under pytest)
```
../../../venv/pytest/src/pygnmi/pygnmi/path_generator.py:17
/var/lib/jenkins/venv/pytest/src/pygnmi/pygnmi/path_generator.py:17: DeprecationWarning: invalid escape sequence \[
if re.match('.*?\[.+?=.+?\].*?', path_in_question):
../../../venv/pytest/src/pygnmi/pygnmi/path_generator.py:18
/var/lib/jenkins/venv/pytest/src/pygnmi/pygnmi/path_generator.py:18: DeprecationWarning: invalid escape sequence \[
split_list = re.findall('.*?\[.+?=.+?\].*?', path_in_question)
../../../venv/pytest/src/pygnmi/pygnmi/path_generator.py:22
/var/lib/jenkins/venv/pytest/src/pygnmi/pygnmi/path_generator.py:22: DeprecationWarning: invalid escape sequence \[
temp_key, temp_value = …
```
> Fix invalid escapes

- pygnmi/arg_parser.py
- pygnmi/client.py
- pygnmi/path_generator.py
On invoking `logging.debug`, a stream handler gets added to the root logger. Avoid this, so that other child logger's content wont get redirected to the console
The easiest solution is to create a child logger for our use.
```python
❯ python
Python 3.7.3 (default, Jan 22 2021, 20:04:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging
>>> logging.getLogger().handlers
[]
>>> logging.debug('Hi')
>>> logging.getLogger().handlers
[<StreamHandler <stderr> (NOTSET)>]
>>>
```
> Avoid modifying root logger

- pygnmi/client.py
Use 'sorted' to render multiple key=value pairs in alphabetic order
> Apply consistent ordering of keys when rendering paths

- examples/pure_python/subscribe_poll.py
- examples/pure_python/subscribe_stream.py
- pygnmi/client.py
Add new classes `{Stream,Poll,Once}Subscriber` that represent a subscription to a list of paths. That object can be iterated over to process updates from the target as they are available. Methods `subscribe_{stream,poll,once}` of the gNMIclient
return that new class.
The Subscribe RPC is made in a new thread. That has the following advantages:
- by keeping the RPC open, we can request further updates for POLL  subscriptions, or keep receiving notifications for STREAM subscriptions;
- can open several subscriptions to the same target using the same client;
- can add a `get_update` method with a timeout (as  opposed to `next()` that blocks indefinitely until updates are received). 
The updates are returned as dictionaries, as translated with telemetryParser.
> Subscribe to updates in a separate thread

- pygnmi/arg_parser.py
- pygnmi/artefacts/messages.py
- pygnmicli.py
Refactors the argument parser to use the common argparse library, as
well as adding proper support for set and subscribe operations in the
various different modes.
For the set operations, when doing an update or replace, an additional parameter `--file` is expected, that contains valid JSON to push to the device.
Subscribe stream, once and poll (via an interactive prompt) are supported.
I've tried to keep the arguments as close to the original as possible. I've also included support for the additional certificate options (root certificate and keyfile). Below is the help string output with the changes
```
$ ./pygnmicli.py -h
usage: pygnmicli.py [-h] -t TARGET [-u USERNAME] [-p PASSWORD] [-c PATH_CERT] [-k PATH_KEY] [-r PATH_ROOT] [-O OVERRIDE] [-i] [-o …
```
> Add working support for set and subscribe to cli wrapper pygnmicli.py

- pygnmi/__init__.py
- pygnmi/path_generator.py
- tests/test_xpath.py
Hi,
This addresses the issue https://github.com/akarneliuk/pygnmi/issues/40 .
The real change is to make `:` special only for the first path element. The current code would look at every path element to set the origin, and any path element past the first one that contained a `:` would the origin to be overwritten. 
In `test_xpath.py` I've included a bunch of example XPATH and the corresponding gNMI paths; taking from both the existing examples and from paths I need to generate. I tried to make really sure that existing documented path would be parsed the same way as the current code; if there is any example where that's not the case, I'll fix that.
>  Only treat ':' specially in the first path element 

- pygnmi/client.py
Adding return type in case of gNMI Set Error  to parse the error string in the automation
as of now there is no return type. 
This can adds retrun type in case of error . 
Please approve and merge 
test Logs :
> //In case of gNMI Set error  
> 
> `------------------------------------------------
> Host: 10.127.60.177:57400
> Error: gNMI commit-request: operation-failed: Subsystem(7331), Code(9): cerrno 0x4e519200: Slot 1 claimed by Cisco Native config. Hence, Terminal device can't be accepted: Cisco-IOS-XR-terminal-device-cfg:logical-channels/channel[channel-index = '3027']/logical-channel-assignments/logical-channel-assignment[assignment-index = '1']/logical-channel-id
> GRPC ERROR Host: 10.127.60.177:57400, Error: gNMI commit-request: operation-failed: Subsystem(7331), Code(9): cerrno …
> Adding return type in case of gNMI Set Error

- pygnmi/client.py
If grpc_options is not passed to __init__() a default list is
constructed. This argument is created once when the method is defined,
thus meaning all instances of gNMIclient ever created will share it. As
this list is later modified (e.g. in the case of skip_verify=True) all
instances share common options. This leads to connection failures and
can result in only one working GNMI connection per program launch.
For details on this type of error see also here:
https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments
> Do not keep global state for grpc_options

- pygnmi/client.py
Heyhey, I wrote this before the release of 0.8.0, i.e. before you commented out the `except` in `get()`, so I guess there's a decision to make! In my proposal we wrap all exceptions inside the `gNMIException`, which is more the behavior of pre-0.8.0. If you want though I can also remove the `except Exception` handlers in `get()` and `set()`, so we only handle the grpc internal exceptions. What do you think?
Also, see commit messages for details. This is a breaking change of the error handling behavior of `set()` as exceptions are raised and not returned. On the other hand this seems to be the way things once were, as `set_with_retry()` clearly expects `set()` to raise a grpc exception.
> Same exception behavior for `set()` and `get()` + `set_with_retry()` fix

- pygnmi/client.py
Exception said that replace was in a wrong format but actually update
was (same as the log.error() message).
> Correct wrong operation name in exception text

- pygnmi/create_gnmi_path.py
- tests/test_00_create_xpath.py
This is valid where there are multiple keys and not all are mandatory, as is the case in ietf-alarms.yang for alarm-type-qualifier
This was previously accepted prior to the rework of the gnmi_path_generator function. I've added a unit-test along with the change, and ensured existing tests still pass.
For a bit more context on this specific case, since I originally thought it wasn't valid to have an empty key, someone else had the same question and outlines the specific part of the model: https://discuss.tail-f.com/t/how-to-access-list-element-on-the-key-which-is-empty/3602
> Support keys with no value in gnmi_path_generator

- pygnmi/client.py
In this patch I re-use in the get() the same encoding defined in the set() (if any). Using the default/automatic encoding the device I'm using it with doesn't return any data, I have to explicitly set it to `json_ietf`.
The current code shows diff for the states values, for example when enabling an interface. As the "set" action modifies configuration, it seems cleaner to me to only show diffs of configuration elements. For that, this patch sets the "datatype" to "config".
> pre/post diff: define encoding and datatype

- pygnmi/client.py
I noticed the root logger being used, presumably unintentionally:
```
INFO     pygnmi.client:client.py:302 Collecting Capabilities...
INFO     pygnmi.client:client.py:342 Collection of Capabilities is successfull
INFO     root:client.py:269 Selected encoding 'json_ietf' based on capabilities
> Stop using root logger in client.py

- pygnmi/client.py
For troubleshooting purposes we need to run our automation (and thus pygnmi) from our laptop instead of prod servers.
GRPC supports the "grpc_proxy" env-var [out of the box](https://github.com/grpc/grpc/blob/master/doc/core/default_http_proxy_mapper.md), but pygnmi does additional certificate verification.
Unfortunately ssl.get_server_certificate doesn't support proxies, so we have to handle it at lower level (the code is greatly inspired by https://stackoverflow.com/questions/53587700).
You can then use it with for example:
`grpc_proxy=http://proxy:8080 python3 test-gnmi3.py`
> Add proxy support

- pygnmi/client.py
This PR resolves an issue where an OSError was being thrown when trying to access terminal size in non-TTY environments like Docker containers. The error was evident when debug=True.
Tested in Docker container to verify the function now operates correctly in these environments.
> fix: debug=True prevents non-tty environment from executing

- pygnmi/tools.py
Current code returns the error at line 153 when `show_diff` is defined in gNMIclient.
`UnboundLocalError: cannot access local variable 'result_list' where it is not associated with a value`
> diff_openconfig: define result_list sooner

- pygnmi/client.py
https://github.com/akarneliuk/pygnmi/pull/22 missed to change usage to logger module instead of logging.
This PR fixes it.
> Fixing log messages to use logger instead of logging

- pygnmi/client.py
A try/except block is added in the `enqueue_updates` method to catch any exceptions during the subscription process. These exceptions are stored in a new attribute `self.error`, making them accessible in the main thread.
As a result of this change, the caller should check `self.error` after each operation to handle any potential exceptions raised in the child thread.
> Add error propagation from child thread to main thread

- pygnmi/client.py
json.dumps causes an issue with escape characters. A CLI command like ```"banner login ^TEST\nBANNER\nLOGIN^"```
gets converted to ```"banner login ^TEST\\nBANNER\\nLOGIN^"```. This fixes that issue.
> Changes to u_val

- pygnmi/client.py
Hi @akarneliuk 
Finally had time to work on committing the bytes_val, but also added a recent find that leaflist_val is not being processed either.
For bytes_val, it is just converting the ieeefloat32 value correctly, and for leaflist_val, it looks like so:
MainThread_2024-03-07 10:19:23,121_gnmi_subscribe_INFO_telemetry_entry={'update': {'update': [{'path': 'system/processes/process[pid=5983]/state/args', 'val': '-C /etc/dnsmasq.conf -h -H /etc/hosts --pid-file=/var/run/dnsmasq.pid'}], 'timestamp': 1709602406601003300}, 'sync_response': True}
> adding bytes_val and leaflist_val with string_val parsing

- pygnmi/client.py
A previous change that I made, caused cases like:
```
path: "openconfig-system:system/config/hostname"
value: "abcd"
```
Where the path was the to the leaf node and the value a string to break.
This PR fixes that while also preventing JSON encoding for ascii_val
> Change to u_val

- pygnmi/client.py
There was previously no way to specify no prefix block before. This adds support for that.
The default value of prefix has been changed to None. To specify an empty prefix, "" must be passed to the function.
> Add support for empty request / no prefix

- pygnmi/client.py
The timeout parameter is not used in this function, so we dont have a way to set timeout for the subscription. This change will fix that.
> Passing the timeout to the subscribe Stub

- pygnmi/client.py
Previously, only str values were supported as the value of a leaflist_val. This extends the code to also support TypedValues with json and json_ietf formats, for both subscriptions and get.
> Properly handle TypedValue as leaflist_val

- pygnmi/client.py
Threads are not joined properly in gRPC and cause an exception on the Python side.
The connection termination is usually okay and shouldn't crash scripts.
The workaround allows joining the the enqueue_updates thread properly.
> Work around gRPC issue. 
